/**
 * Universal File Download and Role Matching Utilities
 */

export const matchesStageRole = (empRole = '', stageKey = '') => {
  const r = (empRole || '').toLowerCase().trim();
  const s = (stageKey || '').toLowerCase().trim();

  if (!r || !s) return false;

  if (s.includes('research')) {
    return r.includes('research') || r.includes('script');
  }
  if (s.includes('anchor')) {
    return r.includes('anchor') || r.includes('host') || r.includes('presenter');
  }
  if (s.includes('production') || s.includes('shoot') || s.includes('camera')) {
    return r.includes('prod') || r.includes('camera') || r.includes('shoot') || r.includes('cinemat');
  }
  if (s.includes('editor') || s.includes('edit')) {
    return r.includes('edit') || r.includes('cutter');
  }
  if (s.includes('thumbnail') || s.includes('thumb') || s.includes('design')) {
    return r.includes('thumb') || r.includes('design') || r.includes('artist') || r.includes('graphic');
  }
  if (s.includes('strategist') || s.includes('strat')) {
    return r.includes('strat') || r.includes('manager') || r.includes('lead');
  }

  return r.includes(s) || s.includes(r);
};

export const handleDownloadOrOpenFile = (fileUrlOrName, defaultFileName = 'Script-Document.docx') => {
  if (!fileUrlOrName) {
    alert('No document link or attachment available for this task.');
    return;
  }

  const trimmed = String(fileUrlOrName).trim();
  const isUrl = /^(https?:\/\/|blob:|data:)/i.test(trimmed);

  if (isUrl) {
    if (trimmed.startsWith('data:') || trimmed.startsWith('blob:')) {
      const a = document.createElement('a');
      a.href = trimmed;
      a.download = defaultFileName;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      return;
    }

    const isDirectDownload = /\.(docx|doc|pdf|txt|mov|mp4|png|jpg|jpeg|wav|mp3|zip)($|\?)/i.test(trimmed);
    if (isDirectDownload) {
      const a = document.createElement('a');
      a.href = trimmed;
      a.download = defaultFileName;
      a.target = '_blank';
      a.rel = 'noopener noreferrer';
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      return;
    }

    window.open(trimmed, '_blank', 'noopener,noreferrer');
    return;
  }

  const fileName = trimmed.endsWith('.docx') || trimmed.endsWith('.doc') ? trimmed : `${trimmed}.docx`;
  const content = [
    '=====================================================',
    'YOUTUBE PRODUCTION SCRIPT ATTACHMENT',
    `File: ${fileName}`,
    'Generated by YT-Ops Central Production Studio',
    `Timestamp: ${new Date().toLocaleString()}`,
    '=====================================================',
    '',
    'This file represents the Word script attachment synced for this video project.',
    'To view online collaborative live edits, please open the linked Google Docs Script Draft.',
  ].join('\n');

  const blob = new Blob([content], {
    type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  });
  const blobUrl = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = blobUrl;
  a.download = fileName;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(blobUrl), 1500);
};

/**
 * Defensively extracts and validates a clean external URL.
 * Handles plain URLs, JSON-stringified URLs, or objects without breaking rendering.
 */
export const sanitizeExternalUrl = (rawVal) => {
  if (!rawVal) return '';
  if (typeof rawVal === 'string') {
    let trimmed = rawVal.trim();
    if (!trimmed) return '';
    // If it's JSON stringified (e.g. '"https://drive.google.com/..."' or '{"url":"..."}')
    if (trimmed.startsWith('"') && trimmed.endsWith('"')) {
      try {
        trimmed = JSON.parse(trimmed);
      } catch {
        trimmed = trimmed.replace(/^"|"$/g, '');
      }
    } else if (trimmed.startsWith('{')) {
      try {
        const parsed = JSON.parse(trimmed);
        trimmed = parsed.url || parsed.link || parsed.raw_footage_url || parsed.audio_file_url || '';
      } catch {
        // keep as is
      }
    }
    return typeof trimmed === 'string' ? trimmed.trim() : '';
  }
  if (typeof rawVal === 'object' && rawVal !== null) {
    return rawVal.url || rawVal.link || rawVal.raw_footage_url || rawVal.audio_file_url || '';
  }
  return String(rawVal).trim();
};
